---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: .
  project:
    - ./tsconfig.json

ignorePatterns:
  - lib/
  - dist/
  - tests/doc/
  - karma.conf.ts

plugins:
  - '@typescript-eslint'

env:
  es6: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

rules:
  # extra rules
  arrow-parens: error
  eqeqeq: error
  grouped-accessor-pairs: error
  no-console: error
  no-extra-parens: error
  no-loss-of-precision: error
  no-sequences: error
  no-template-curly-in-string: error
  no-throw-literal: error
  no-unused-expressions: error
  no-useless-concat: error
  no-var: error
  quotes: [error, single]
  radix: error
  semi: error
  # only sort inside groups, not between separate import lines
  sort-imports: [error, {ignoreDeclarationSort: true}]
  sort-keys: [error, asc, {minKeys: 4}]
  # disabled rules
  '@typescript-eslint/no-inferrable-types': off
