trailingComma: es5
tabWidth: 4
singleQuote: true
printWidth: 100
overrides:
  - files:
      - '*.yml'
    options:
      tabWidth: 2
  - files:
      - '*.json'
    options:
      tabWidth: 2
  - files:
      - '*.html'
    options:
      printWidth: 150
