name: Documentation

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    # Check all PR

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: update npm
        run: npm install -g npm
      - uses: bahmutov/npm-install@v1
      - name: build documentation
        run: npm run docs
      - name: put documentation in the website
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY --branch gh-pages gh-pages
          rm -rf gh-pages/.git

          REF_KIND=$(echo $GITHUB_REF | cut -d / -f2)
          if [[ "$REF_KIND" == "tags" ]]; then
              TAG=${GITHUB_REF#refs/tags/}
              mv dist/docs/ gh-pages/$TAG
          else
              rm -rf gh-pages/latest
              mv dist/docs/ gh-pages/latest
          fi
      - name: deploy to gh-pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages/
          force_orphan: true
