name: Tests
on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  npm-test:
    strategy:
      matrix:
        node-version: ['14', '16']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - name: node & npm version
        run: |
          node --version
          npm --version
      - name: run tests (node & web)
        run: npm test
      - name: collect test coverage
        run: |
          npm run coverage
          npm install -g codecov
          codecov
      - name: ensure all function are used
        run: |
          python scripts/check-used-functions.py
