name: Tests
on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  npm-test:
    strategy:
      matrix:
        node-version: ['12', '13', '14']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npm test
      - run: npx karma start
      - run: npm run coverage
      - run: npm install -g codecov
      - run: codecov
